FROM ubuntu

# 30초 간격으로 특정 사이트 접속 체크, 응답 지연은 30초 이내 들어올 때 까지는 오류 X
HEALTHCHECK --interval=30s --timeout=30s CMD [ "curl", "-f", "http://127.0.0.1", "||", "exit 1" ]

# DB 체크 예시
# HEALTHCHECK --interval=30s --timeout=30s CMD [ "mysqladmin", "ping", "-h", "http://127.0.0.1", "--password=12341234 ", "--slient"]

