# 베이스이미지
FROM ubuntu

# 압축해제 후 추가
ADD web.tar /home/

# URL 다운로드 후 추가
ADD https://github.com/ultralytics/yolov5/blob/master/requirements.txt /home/requirements.txt

# 파일 추가
ADD readme.md /home/readme_docker.md

# 특정 이름으로 시작하는 모든 파일(패턴지정) 추가
ADD po*.txt /home/

# 특정 이름 + 한글자로 시작하는 모든 파일 추가
ADD to?.txt /home/